[package]
name = "pdfplot"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
pdfpdf = {git = "https://github.com/saethlin/pdfpdf"}

[dev-dependencies]
ndarray = "0.12"
